### PR TITLE
Add setup.py and python3 support

### PR DESCRIPTION
**Pull request by zackhsi**
- Add setup.py based on https://github.com/kennethreitz/setup.py.
- Run [python-modernize](https://python-modernize.readthedocs.io/en/latest/) and add a couple fixes for Python3 support.
- Simplify installation instructions.

### CODE REVIEW

**Comment by jszakmeister** [comment]
Why such concern about it being available on PyPI?  I think of PyPI more as being for libraries and frameworks rather than general tools, so it feels a little wrong to be distributing it on PyPI.  I don't believe it's so much simpler to setup than simply copying a file, but I guess I'm in the minority here given the 2 other pull requests for this.  I'm also disappointed that you just went ahead and put it up on PyPI without really discussing it with me--it's a bit presumptuous. :-(  I would have done it myself if I was eager to have it up there.

I'm not too keen on taking Kenneth's work and calling it mine either--it's closer to a wholesale copy rather than just being modeled after his code.  It's also under a different license than my code and that hasn't been documented anywhere.

Don't get me wrong, I appreciate the updates but these little things are important.  Also, it would've been nice to separate out what were fixes from modernize vs. fixes to support python3 vs. adding a setup.py and updating the installation instructions, IMHO.

**Comment by zackhsi** [comment]
PyPI is great as a reliable, versioned store. Editable or otherwise bespoke installations of packages give me... shudders (thought I certainly do them at times) 😄 

Apologies for the publication. Curious what the main hesitations are? Are there attribution changes you would like?

Modernize added the `__future__` imports and updated the print statement. The non-modernize changes were to read the file as a string instead of as bytes, and the `__lt__` was added for [comparisons](https://docs.python.org/3/howto/sorting.html).

**Comment by jszakmeister** [comment]
> PyPI is great as a reliable, versioned store. Editable or otherwise bespoke installations of packages give me... shudders (thought I certainly do them at times) 😄

That's all great, but it's not really a Python library. :-)

> Apologies for the publication. Curious what the main hesitations are? Are there attribution changes you would like?

Several reasons:

1) I didn't feel like it was ready
2) It wasn't Python 3 compatible
3) I'm not sure Python-based utilities should be published via PyPI, which I consider mainly a store for libraries and frameworks
4) Publishing on PyPI doesn't really feel like an easier install step, IMHO

> Modernize added the __future__ imports and updated the print statement. The non-modernize changes were to read the file as a string instead of as bytes, and the __lt__ was added for comparisons.

According to the docs, we really have to implement the full complement of rich comparison operators instead.

Also, simply dropping binary off the file isn't really acceptable.  What encoding is it using?  (Hint: it's platform dependent and may run amok of other issues, and you can't really assume it's UTF-8 either as there are many systems that default to different encodings).  This doesn't really solve that problem.  I think a better answer is required on the encoding front rather than hoping it's going to workout okay, IMHO.  In fact, I think keeping everything as bytes is really the best answer.

**Comment by jszakmeister** [comment]
Can you please take down markdown2ctags from PyPI?  I'm pretty sure it's broken for some encodings in Python 3.  Thanks.

**Comment by jszakmeister** [comment]
Can you try my update-for-python-3 branch?  I don't love the encoding solution, but I think it'll work for more international environments.

**Comment by zackhsi** [comment]
Taken down.

The branch works for me functionally, +1. Thanks for helping out.

**Comment by zackhsi** [comment]
Taken down.

Couple nits on your branch: there is a python2 print statement in the sad path on L285, and version is defined twice. The code works for me functionally, +1.

Thanks for helping out.

I would still push for pypi publication mainly because it is the standard way to distribute Python code, and people are used to `pip install`-ing from pypi. Requiring a local checkout at a well-known path adds friction to the distribution process.

**Comment by jszakmeister** [comment]
> Taken down.

Thank you, I appreciate it.

> Couple nits on your branch: there is a python2 print statement in the sad path on L285, and version is defined twice. The code works for me functionally, +1.

Good catch!  Fixed.

> Thanks for helping out.
> 
> I would still push for pypi publication mainly because it is the standard way to distribute Python code, and people are used to pip install-ing from pypi. Requiring a local checkout at a well-known path adds friction to the distribution process.

Again, that's where I see things differently.  I don't really see PyPI as a place to distribute utilities, but I hear you.  OTOH, being on PyPI still doesn't help those who know nothing of pip and installing Python packages.  Also, people are free to package it and include it as part of a distro... pip isn't the only way to get there.  Of course, you don't really need to checkout anything, simply grab the raw file and put it on your file system.  But you aren't the first person to ask for this, so I'll do it.  I just want to run with this for a while before publishing.

**Comment by jszakmeister** [comment]
I merged my python3 support branch into master.  Closing this, and thank you for testing.

**Comment by jszakmeister** [comment]
@zackhsi Unfortunately, the fact that you registered markdown2ctags is creating a problem with publishing.  Can you add me as an Owner to the project so that I can fix this?  Also, I'll want to take over ownership and remove you from it.  I hope that's okay, but it helps ensure that only what I publish is available.

**Comment by jszakmeister** [comment]
@zackhsi BTW, my pypi id is: jszakmeister

**Comment by zackhsi** [comment]
Done!

**Comment by jszakmeister** [comment]
@zackhsi Sweet.  Thank you!  And we're published now: https://pypi.python.org/pypi/markdown2ctags

**Comment by zackhsi** [comment]
What a bright future we live in :)

**Pull request closed without merging**
